### ISSUE TITLE
2d-matrix-grid only shows 25 rows

### ISSUE THREAD

**Issue by julieb2292** [RallyTechServices/2d-matrix-grid#7]
Even though the app settings has an option to specify how many rows to display, the grid only always shows a max of 25 items.  In the code the max and page size is set to be 25 but there's no pagination and it's not clear where the app settings are being utilized.

**Comment by julieb2292** [comment]
I changed line 304 from: 
showPagingToolbar: false
to:
showPagingToolbar: true

and now it seems to load all of the data, 25 rows at a time, with pagination.  I think that might be all it takes to ensure all the data is always displayed, but I'm not 100% positive so I'm not going to create a pull request (don't want to further break something unintentionally).

**Comment by kcorkan** [comment]
@julieb2292 , good catch!  I made another update for someone else so instead of adding the paging toolbar, I updated the store so that the page size is always the number of records (which I think was the original intent so we don't have to page).  Let me know if this new version works ok for you.  I'll close the issue after I hear back from you.  

If you do want paging, then you could always reenable the showPagingToolbar.  I typically turn off paging for grids where we already are using custom grids like in this case because we have to retrieve all of the data from the server in order to sort the data properly.  I have had unpredictable results with sorting a paged custom store.

**Comment by julieb2292** [comment]
@kcorkan I just installed the new version, and it's still only showing 25 items total in the grid.

I do agree that showing all items on one page is better than turning on paging.

**Comment by julieb2292** [comment]
@kcorkan correction: if I use ugly.txt, it works.  It seems that app.txt was not updated with the changes.  Can we update the app.txt file too or just remove it?

Thanks!

Julie

**Comment by kcorkan** [comment]
Thanks @julieb2292 I removed it as Tyke also saw that.  I'm closing the issue now.  Thanks again for the help and feedback!
